/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export default function SpaceEnv({ ...props }) {
  const group = useRef();
  const bakedTexture = useTexture(
    `${process.env.PUBLIC_URL}/models/baked_floor_small.png`
  );
  const bakedMountains = useTexture(
    `${process.env.PUBLIC_URL}/models/baked_mountains.png`
  );

  const { nodes, materials } = useGLTF(
    `${process.env.PUBLIC_URL}/models/space_env.glb`
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.mountain_1.geometry}>
        <meshBasicMaterial map={bakedMountains} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.mountain_3.geometry}></mesh>
      <mesh
        geometry={nodes.mountain_2.geometry}
        material={nodes.mountain_2.material}
      />
      <mesh geometry={nodes.Plane.geometry}>
        <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
    </group>
  );
}

useGLTF.preload(`${process.env.PUBLIC_URL}/models/space_env.glb`);
