let designData = [
  {
    title: "ClimbWest",
    text: "One of many pieces I designed while working as a graphic designer for the indoor climbing gym, Climbwest. This illustration was designed for pride week in Melbourne and used on the climbing gym's social platforms as well as an A1 print version.",
    imgSrc: "pride.png",
    bgColor: "#1F1F31",
    textTheme: "light",
    size: "big",
  },
  {
    title: "ClimbWest",
    text: "Brand and merchandise design. The design brings together expressive elements of climbing and music culture. The colour palette is bold and emotive and reflects the business' two female owners. ",
    imgSrc: "handshirt.png",
    altImg: "handdesign.png",
    bgColor: "#EDEFF1",
    textTheme: "dark",
    size: "tall",
  },
  {
    title: "ClimbWest",
    text: "Early concept for logo and branding of the climbing gym. The grayscale mockup includes climbing holds and elements found inside and around the climbing gym.",
    imgSrc: "climb.png",
    bgColor: "#fff",
    textTheme: "dark",
    size: "tall",
  },
  {
    title: "Logo Concept",
    text: "As the main product offering of an indoor climbing gym, the climbing routes are arguably the important aspect of this business and communicating how they work to customers is crucial.  ",
    imgSrc: "instagram.png",
    bgColor: "#efefef",
    textTheme: "dark",
    size: "wide",
  },
  {
    title: "Recycle Responsibly",
    text: "Recycling infographic concept designed for Moorland city council. The brief required a short and effectively communicated concept to help residents understand what could and could not be places into the recycling bins.",
    imgSrc: "recycle.png",
    bgColor: "#EEEEEE",
    textTheme: "dark",
    size: "tall",
  },

  {
    title: "Up Unlimited Challenge",
    text: "I designed this poster as the starting point for UpUnlimited's marketing project to engage children climbers while they. Part of the facalities attempt to engage and target returning customers.",
    imgSrc: "ninja.jpg",
    bgColor: "#EEEEEE",
    textTheme: "dark",
    size: "tall",
  },
  {
    title: "Logo Concept",
    text: "The simplest of the three logo's I created for the ClimbWest branding. It was chosen by the owners as the main brand identity.  Final choice of logo for Climb West. This design was chosen by the owners for its simplicity",
    imgSrc: "climb_2.png",
    bgColor: "#EEEEEE",
    textTheme: "dark",
    size: "wide",
  },
  {
    title: "ClimbWest",
    text: "New text",
    imgSrc: "cert.jpg",
    bgColor: "#e1ebf0",
    textTheme: "dark",
    size: "wide",
  },
];

export default designData;
