let designData = [
  {
    title: "Illustration",
    text: "One of many pieces I designed while working as a graphic designer for the indoor climbing gym, Climbwest. This illustration was designed for pride week in Melbourne and used on the climbing gym's social platforms as well as an A1 print version in the gym.",
    imgSrc: "pride.png",
    bgColor: "#1F1F31",
    textTheme: "light",
    size: "big",
  },
  {
    title: "T-Shirt Branding",
    text: "Brand and merchandise design. The design brings together expressive elements of climbing and music culture (No that's not a toothbrush!). The colour palette is bold and emotive and tries to reflect the business's two female owners.",
    imgSrc: "handshirt.png",
    altImg: "handdesign.png",
    bgColor: "#EDEFF1",
    textTheme: "dark",
    size: "tall",
  },
  {
    title: "Logo Design",
    text: "Early concept for the logo and branding of the ClimbWest gym. The grayscale mockup includes climbing holds and elements found inside and around the climbing gym such as walls and climbing holds.",
    imgSrc: "climb.png",
    bgColor: "#d3d3d3",
    textTheme: "dark",
    size: "tall",
  },
  {
    title: "Social Media Illustrations",
    text: "As the main product offering of an indoor climbing gym, the climbing routes are arguably the important aspect of this business and communicating how they work to customers is crucial.  ",
    imgSrc: "instagram.png",
    bgColor: "#efefef",
    textTheme: "dark",
    size: "wide",
  },
  {
    title: "Recycle Responsibly",
    text: "Recycling infographic concept designed for Moorland city council to be placed on the front of recycling bins. The brief required a short and effective way to communicate and help residents understand what could and could not be places into the recycling bins.",
    imgSrc: "recycle.png",
    bgColor: "#EEEEEE",
    textTheme: "dark",
    size: "tall",
  },

  {
    title: "Up Unlimited Challenge",
    text: "This poster was designed as the starting point for UpUnlimited's marketing project to engage children climbers while they.... Teenagers or parents could scan the QR code to launch the app and begin one of the many activity challanges at the facility.",
    imgSrc: "ninja.jpg",
    bgColor: "#EEEEEE",
    textTheme: "dark",
    size: "tall",
  },
  {
    title: "Plant a tree Certificate",
    text: "The aTree project is all about empowering people to help revitalise natural ecosystems. I designed this print and digital certificate for their.. ",
    imgSrc: "cert.jpg",
    bgColor: "#eeeeee",
    textTheme: "dark",
    size: "wide",
  },
  {
    title: "Logo Illustration",
    text: "The simplest of the three logo's I created for the ClimbWest branding. It was chosen by the owners as the main brand identity for its simplicity",
    imgSrc: "climb_2.png",
    bgColor: "#EEEEEE",
    textTheme: "dark",
    size: "wide",
  },
];

export default designData;
