let designData = [
  {
    title: "Illustration",
    text: "One of many pieces I designed while working as a graphic designer for the indoor climbing gym, Climbwest. This illustration was designed for pride week in Melbourne and used on the climbing gym's social platforms as well as an A1 print version in the gym.",
    imgSrc: "pride.png",
    bgColor: "#1F1F31",
    textTheme: "light",
    size: "big",
  },
  {
    title: "T-Shirt Branding",
    text: "I designed this illustration to be printed on the back of t-shirts and sold in ClimbWest's merchandise shop. The design brings together expressive elements of climbing culture (No, that's not a toothbrush!) while the colour palette is bold and emotive -reflecting the business's two female owners.",
    imgSrc: "handshirt.png",
    altImg: "handdesign.png",
    bgColor: "#EDEFF1",
    textTheme: "dark",
    size: "tall",
  },
  {
    title: "Logo Design",
    text: "Prior to the gym openeing I was tasked with designing two different logo's for the business. This grayscale design was the first of two early concepts and includes climbing volumes and elements found inside and around the gym.",
    imgSrc: "climb.png",
    bgColor: "#d3d3d3",
    textTheme: "dark",
    size: "tall",
  },
  {
    title: "Social Media Illustrations",
    text: "Unsuprisingly, social media is the main channel of communication between many small businesses and their customers. I was tasked in designing some graphics to communicate some recent changes in the gyms operating procedures in image format for their social channels. ",
    imgSrc: "instagram.png",
    bgColor: "#efefef",
    textTheme: "dark",
    size: "wide",
  },
  {
    title: "Recycle Responsibly",
    text: "Recycling infographic concept designed for Moorland city council to be placed on the front of recycling bins. The design brief required a short and effective way to communicate and help residents understand what could and could not be places into the recycling bins.",
    imgSrc: "recycle.png",
    bgColor: "#EEEEEE",
    textTheme: "dark",
    size: "tall",
  },

  {
    title: "Up Unlimited Challenge",
    text: "This poster was designed as the starting point for UpUnlimited's marketing project to engage children while they visited the facility. Teenagers or parents could scan the QR code to launch the accompanying app and begin one of the many activity challanges.",
    imgSrc: "ninja.jpg",
    bgColor: "#EEEEEE",
    textTheme: "dark",
    size: "tall",
  },
  {
    title: "Plant a tree Certificate",
    text: "The aTree project is all about empowering people to help revitalise natural ecosystems. This illustration was used as a digital certificate sent to customers after donating and planting a tree. It was important to align the 'feel' of the certificate with the brand to give a sense of purpose and provide the customer with something tangible after their donation",
    imgSrc: "cert.jpg",
    bgColor: "#eeeeee",
    textTheme: "dark",
    size: "wide",
  },
  {
    title: "Logo Illustration",
    text: "The second of two logo's I designed for ClimbWest indoor climbing gym. The simple and clean logo contains elements of the outdoors and geometric shapes often used as indoor climbing holds. It was chosen by the owners for its simplicity and minimalism. Currently being used in both print and digital as the main brand identity",
    imgSrc: "climb_2.png",
    bgColor: "#EEEEEE",
    textTheme: "dark",
    size: "wide",
  },
];

export default designData;
